name: destroy-artifacts

on:
  push:
    branches:
      - main

jobs:
  delete-artifacts:
    name: Delete artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: build
